version: '3.8'

services:

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true